image: ruby:latest

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8
  
cache:
    paths:
       - vendor/
       
       
before_script:
    - bundle install --path vendor
  
test:
    stage: test
    script:
        - echo $CI_JOB_STAGE
        - bundle exec jekyll build -d test
    artifacts:
       paths:
       - test
    except:
        - master
pages:
  stage: deploy
  script:
  - gem install jekyll
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master