#General settings


title: Portfolio Content
author: Callam Josef Jackson-Sem
email: jackcj1@student.op.ac.nz
description: >- # this means to ignore newlines until "baseurl:"

header_pages:
    - about.md

show_exerpts: false
incremental: true
regenerate: true

minima:
    date_format: "%b %-d, %Y"

baseurl: "/callam-project/" # the subpath of your site, e.g. /blog
url: "https://jackcj1.pages.op-bit.nz/callam-project" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
gitlab_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-compose
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
